# Render service configuration - despliegue desde la rama `render-deploy`
services:
  - type: web
    name: petstore-backend
    env: docker
    branch: render-deploy
    plan: starter
    # When using Docker, Render will build the Dockerfile in the repo root.
    dockerfilePath: Dockerfile
    # No incluyas secretos aquí. Define las siguientes variables en la UI de Render:
    # SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ""
      - key: SPRING_DATASOURCE_USERNAME
        value: ""
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
    # If you don't have Spring Actuator, set a simple path like '/' instead.
    healthCheckPath: "/"
